import JSP523.Rank4.GraphPairAccounting

/-!
# Unique-pair record interface

This file turns a combinatorial injection of records into unique common
pairs into the numerical bound used by the colored-slot payment.  Records
may be constructed from any auxiliary finite object; only injectivity and
the unique-common-neighbor property are needed here.
-/

namespace JSP523.Rank4

variable {α : Type*} [Fintype α] [DecidableEq α]

omit [DecidableEq α] in
/-- Common-neighbor multiplicity is monotone under a graph inclusion. -/
theorem graphCommonMultiplicity_le_of_adj_mono
    {F G : SimpleGraph α} [DecidableRel F.Adj] [DecidableRel G.Adj]
    (hAdj : ∀ a b, F.Adj a b → G.Adj a b) (a b : α) :
    graphCommonMultiplicity F a b ≤ graphCommonMultiplicity G a b := by
  classical
  unfold graphCommonMultiplicity
  apply Finset.card_le_card
  intro z hz
  rcases Finset.mem_filter.mp hz with ⟨hza, hzb⟩
  have hza' : F.Adj a z := by simpa [SimpleGraph.mem_neighborFinset] using hza
  have hzaG : G.Adj a z := hAdj a z hza'
  have hzbG : G.Adj b z := hAdj b z hzb
  exact Finset.mem_filter.mpr
    ⟨by simpa [SimpleGraph.mem_neighborFinset] using hzaG, hzbG⟩

/-- Ordered off-diagonal vertex pairs with exactly one common neighbor. -/
def orderedUniquePairSet (F : SimpleGraph α) [DecidableRel F.Adj] :
    Finset (α × α) :=
  Finset.univ.filter fun p =>
    p.1 ≠ p.2 ∧ graphCommonMultiplicity F p.1 p.2 = 1

theorem orderedUniquePairSet_card_eq
    (F : SimpleGraph α) [DecidableRel F.Adj] :
    ((orderedUniquePairSet F).card : ℚ) = orderedUniquePairCount F := by
  classical
  unfold orderedUniquePairSet orderedUniquePairCount
  rw [Finset.card_filter]
  rw [Fintype.sum_prod_type]
  push_cast
  apply Finset.sum_congr rfl
  intro x _
  calc
    (∑ y : α, if x ≠ y ∧ graphCommonMultiplicity F x y = 1 then
        (1 : ℚ) else 0) =
      ∑ y ∈ Finset.univ.filter (fun y : α => y ≠ x),
        if graphCommonMultiplicity F x y = 1 then (1 : ℚ) else 0 := by
          simp only [Finset.sum_filter]
          congr 1
          ext y
          by_cases h : y = x
          · simp [h]
          · have hxy : x ≠ y := Ne.symm h
            simp [h, hxy]
    _ = ∑ y ∈ Finset.univ.erase x,
        if graphCommonMultiplicity F x y = 1 then (1 : ℚ) else 0 := by
          congr 1
          ext y
          simp

/-- Any finite record family injecting into distinct ordered unique pairs
has size at most the cardinality of the ordered unique-pair set. -/
theorem unique_records_card_le_set
    (F : SimpleGraph α) [DecidableRel F.Adj]
    {ρ : Type*} [Fintype ρ] [DecidableEq ρ]
    (record : ρ → α × α)
    (hInjective : Function.Injective record)
    (hUnique : ∀ r, (record r).1 ≠ (record r).2 ∧
      graphCommonMultiplicity F (record r).1 (record r).2 = 1) :
    Fintype.card ρ ≤ (orderedUniquePairSet F).card := by
  classical
  let imageSet : Finset (α × α) := Finset.univ.image record
  have hImageSubset : imageSet ⊆ orderedUniquePairSet F := by
    intro p hp
    obtain ⟨r, _, hr⟩ := Finset.mem_image.mp hp
    subst p
    exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, hUnique r⟩
  have hImageCard : imageSet.card = Fintype.card ρ := by
    rw [Finset.card_image_of_injective _ hInjective]
    simp
  have hCard := Finset.card_le_card hImageSubset
  omega

/-- Rational form of `unique_records_card_le_set`, in the exact
normalization consumed by `graphDeficit_marked` and colored payments. -/
theorem unique_records_le_ordered_count
    (F : SimpleGraph α) [DecidableRel F.Adj]
    {ρ : Type*} [Fintype ρ] [DecidableEq ρ]
    (record : ρ → α × α)
    (hInjective : Function.Injective record)
    (hUnique : ∀ r, (record r).1 ≠ (record r).2 ∧
      graphCommonMultiplicity F (record r).1 (record r).2 = 1) :
    (Fintype.card ρ : ℚ) ≤ orderedUniquePairCount F := by
  have hcard := unique_records_card_le_set F record hInjective hUnique
  have hq : (Fintype.card ρ : ℚ) ≤ ((orderedUniquePairSet F).card : ℚ) :=
    Nat.cast_le.mpr hcard
  rw [orderedUniquePairSet_card_eq] at hq
  exact hq

/-- The ordered pair records generated by a vertex's neighborhood are
unique pairs whenever every two distinct neighbors have just that vertex
as their common neighbor. This is the graph-level extraction used at a
fully selected colored slot. -/
def neighborPairRecords (F : SimpleGraph α) [DecidableRel F.Adj]
    (z : α) : Finset (α × α) :=
  ((F.neighborFinset z).product (F.neighborFinset z)).filter
    fun p => p.1 ≠ p.2

theorem neighborPairRecords_subset_unique
    (F : SimpleGraph α) [DecidableRel F.Adj] (z : α)
    (hUnique : ∀ a ∈ F.neighborFinset z, ∀ b ∈ F.neighborFinset z,
    a ≠ b → graphCommonMultiplicity F a b = 1) :
    neighborPairRecords F z ⊆ orderedUniquePairSet F := by
  intro p hp
  unfold neighborPairRecords at hp
  rw [Finset.mem_filter] at hp
  rcases hp with ⟨hprod, hne⟩
  rcases Finset.mem_product.mp hprod with ⟨ha, hb⟩
  exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, hne,
    hUnique p.1 ha p.2 hb hne⟩

theorem neighborPairRecords_card_le_ordered_count
    (F : SimpleGraph α) [DecidableRel F.Adj] (z : α)
    (hUnique : ∀ a ∈ F.neighborFinset z, ∀ b ∈ F.neighborFinset z,
      a ≠ b → graphCommonMultiplicity F a b = 1) :
    ((neighborPairRecords F z).card : ℚ) ≤ orderedUniquePairCount F := by
  have h := Finset.card_le_card (neighborPairRecords_subset_unique F z hUnique)
  have hq : ((neighborPairRecords F z).card : ℚ) ≤
      ((orderedUniquePairSet F).card : ℚ) := Nat.cast_le.mpr h
  rw [orderedUniquePairSet_card_eq] at hq
  exact hq

/-- The dependent family of directed unique-pair records over a family of
graphs. -/
def FamilyUniquePairRecord {β : Type*} [Fintype β]
    (F : β → SimpleGraph α) [∀ i, DecidableRel (F i).Adj] :=
  Σ i : β, {p : α × α // p ∈ orderedUniquePairSet (F i)}

noncomputable instance familyUniquePairRecordFintype {β : Type*}
    [Fintype β] (F : β → SimpleGraph α) [∀ i, DecidableRel (F i).Adj] :
    Fintype (FamilyUniquePairRecord F) := by
  classical
  letI (i : β) : Fintype {p : α × α // p ∈ orderedUniquePairSet (F i)} :=
    Fintype.ofFinset (orderedUniquePairSet (F i)) (fun _ => Iff.rfl)
  change Fintype (Σ i : β, {p : α × α // p ∈ orderedUniquePairSet (F i)})
  exact inferInstance

set_option linter.style.haveILetI false in
theorem familyUniquePairRecord_card_eq {β : Type*} [Fintype β]
    (F : β → SimpleGraph α) [∀ i, DecidableRel (F i).Adj] :
    (Fintype.card (FamilyUniquePairRecord F) : ℚ) =
      ∑ i : β, orderedUniquePairCount (F i) := by
  classical
  letI (i : β) : Fintype {p : α × α // p ∈ orderedUniquePairSet (F i)} :=
    Fintype.ofFinset (orderedUniquePairSet (F i)) (fun _ => Iff.rfl)
  change (Fintype.card (Σ i : β, {p : α × α // p ∈ orderedUniquePairSet (F i)}) : ℚ) = _
  rw [Fintype.card_sigma]
  push_cast
  apply Finset.sum_congr rfl
  intro i _
  rw [Fintype.card_coe]
  exact orderedUniquePairSet_card_eq (F i)

/-- If a finite family of undirected pair records injects in both
orientations into the unique-pair records of its assigned graphs, then its
size is at most half the total directed unique-pair count. -/
theorem undirected_record_family_le_half_ordered_count
    {β ρ : Type*} [Fintype β] [Fintype ρ] [DecidableEq ρ]
    (F : β → SimpleGraph α) [∀ i, DecidableRel (F i).Adj]
    (owner : ρ → β) (ends : ρ → α × α)
    (hne : ∀ r, (ends r).1 ≠ (ends r).2)
    (hUnique : ∀ r,
      graphCommonMultiplicity (F (owner r)) (ends r).1 (ends r).2 = 1)
    (hOrientInjective : Function.Injective (fun ro : ρ × Bool =>
      (owner ro.1, if ro.2 then (ends ro.1).swap else ends ro.1))) :
    (Fintype.card ρ : ℚ) ≤
      (∑ i : β, orderedUniquePairCount (F i)) / 2 := by
  classical
  let orientedEnds : ρ × Bool → α × α := fun ro =>
    if ro.2 then (ends ro.1).swap else ends ro.1
  have oriented_mem : ∀ ro, orientedEnds ro ∈ orderedUniquePairSet (F (owner ro.1)) := by
    intro ro
    have hne' : (orientedEnds ro).1 ≠ (orientedEnds ro).2 := by
      dsimp [orientedEnds]
      cases ro.2
      · exact hne ro.1
      · exact (hne ro.1).symm
    have hUnique' : graphCommonMultiplicity (F (owner ro.1))
        (orientedEnds ro).1 (orientedEnds ro).2 = 1 := by
      dsimp [orientedEnds]
      cases ro.2
      · exact hUnique ro.1
      · simpa [graphCommonMultiplicity_symm] using hUnique ro.1
    exact Finset.mem_filter.mpr ⟨Finset.mem_univ _, hne', hUnique'⟩
  let key : ρ × Bool → FamilyUniquePairRecord F := fun ro =>
    ⟨owner ro.1, ⟨orientedEnds ro, oriented_mem ro⟩⟩
  have hkey : Function.Injective key := by
    intro ⟨r, o⟩ ⟨s, o'⟩ h
    have hval :
        (owner r, orientedEnds (r, o)) =
          (owner s, orientedEnds (s, o')) := by
      apply Prod.ext
      · exact congrArg Sigma.fst h
      · exact congrArg (fun q : FamilyUniquePairRecord F => q.2.1) h
    exact hOrientInjective hval
  have hcard := Fintype.card_le_of_injective key hkey
  have hprod : Fintype.card (ρ × Bool) = 2 * Fintype.card ρ := by
    rw [Fintype.card_prod]
    simp [Fintype.card_bool, Nat.mul_comm]
  have hqc : (Fintype.card (ρ × Bool) : ℚ) ≤
      (Fintype.card (FamilyUniquePairRecord F) : ℚ) := Nat.cast_le.mpr hcard
  rw [hprod, familyUniquePairRecord_card_eq F] at hqc
  rw [le_div_iff₀ (by norm_num : (0 : ℚ) < 2)]
  push_cast at hqc ⊢
  nlinarith

end JSP523.Rank4
